name: cli_example
description: DartSV CLI Demo Application
version: 0.3.0
homepage: https://github.com/twostack/cli-example
author: Stephan M. February <stephan@werkswinkel.com>

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  hex: ^0.1.2
  asn1lib: ^0.5.8
  pointycastle: ^1.0.1
  collection: ^1.14.11
  sprintf: ^4.0.2
  http: ^0.12.0+2
  dartsv: ^0.3.0
  bip39: ^1.0.3


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
