name: dartsv
description: Dart Library for interacting with the Bitcoin network. This library is especially well-suited for use in developing Flutter applications.
version: 0.3.1
homepage: https://github.com/twostack/dartsv

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  hex: ^0.1.2
  asn1lib: ^0.5.15
  resource: ^2.1.5
  pointycastle: ^1.0.1
  collection: ^1.14.11
  sprintf: ^4.0.2
  unorm_dart: ^0.1.1
  buffer: ^1.0.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^4.0.0
